# -*- coding: utf-8 -*-
"""rawToId.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nX9ben5knBOl4AE8__ZqOmuoK62aF4v2
"""

import json
import random

def genAPI(jq1 = 1111009710504092045635, jq2 = 1621425006464, jq3 = 1621425006465):
    while True:
        jq1 += random.randrange(-2500, 2500)
        jq2 += random.randrange(-2500, 2500)
        jq3 += random.randrange(-2500, 2500)
        yield (jq1, jq2, jq3)

myAPI = genAPI()

def trimLine(l):
    '''
    IN -> string, line
    OUT -> dict 
    '''
    oBracket = l.find('(')
    return json.loads(l[oBracket + 1 : -1])

def genReader(file_name):
    '''
    IN -> string, file path
    OUT -> string, generator that yields one line at a time
    '''
    for row in open(file_name, "r"):
        yield trimLine(row.strip())

def rawToId(inFile, outFile):

    sample = genReader(inFile)

    j1, j2, j3 = next(myAPI)

    with open(outFile, 'a') as outFile:
        count = 0

        for item in sample:
            currentLine = next(sample)
            for i in currentLine['records']:
                count += 1
                if count % 500 == 0:
                    print(count)
                # outFile.write(i['id'])
                outFile.write(f'https://api.iag.bg/cgi-bin/e_tickets/get.cgi?lng=bg&session=000&user_id=0&ticket_id={i["id"]}&digest=xxxn&callback=jQuery{j1}_{j2}&_={j3}')
                outFile.write('\n')

if __name__ == "__main__":
    rawToId(inFile = 'tickets2021raw.txt', outFile = 'tickets2021url.txt')